<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="accounts.service.AccountServiceTest" tests="2" skipped="0" failures="0" errors="0" timestamp="2024-04-21T16:37:14" hostname="MASH-PF4D8NPZ" time="0.287">
  <properties/>
  <testcase name="updateAccountWithInvalidId()" classname="accounts.service.AccountServiceTest" time="0.276"/>
  <testcase name="createAccountWithDuplicateEmail()" classname="accounts.service.AccountServiceTest" time="0.01"/>
  <system-out><![CDATA[21:37:14.744 [Test worker] INFO com.midas.app.services.AccountServiceImpl -- Update account request received with account Id 1 and account details class UpdateAccountDto {
    firstName: abc
    lastName: xyz
    email: abc@gmail.com
}
21:37:14.744 [Test worker] ERROR com.midas.app.services.AccountServiceImpl -- No user found against given id: 1
21:37:14.757 [Test worker] INFO com.midas.app.services.AccountServiceImpl -- Create account request received: class CreateAccountDto {
    firstName: abc
    lastName: xyz
    email: abc@gmail.com
}
21:37:14.758 [Test worker] ERROR com.midas.app.services.AccountServiceImpl -- unable to add user because user already exist with email: abc@gmail.com
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
